#!/bin/sh

host="$(cat /etc/hostname)"
os='Arch Linux'
kernel="$(uname -sr | rev | cut -c 9- | rev)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename "${SHELL}")"
memory="$(free -h | grep Mem | awk '{print $3 }') / $(free -h | grep Mem | awk '{print $2 }')"

## UI DETECTION
parse_rcs() {
	for f in "${@}"; do
		wm="$(tail -n 1 "${f}" 2> /dev/null | cut -d ' ' -f 2)"
		[ -n "${wm}" ] && echo "${wm}" && return
	done
}

rcwm="$(parse_rcs "${HOME}/.xinitrc" "${HOME}/.xsession")"
uitype='UI'
if [ -n "${DE}" ]; then
	ui="${DE}"
elif [ -n "${WM}" ]; then
	ui="${WM}"
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
elif [ -n "${rcwm}" ]; then
	ui="${rcwm}"
elif [ -n "${XDG_SESSION_TYPE}" ]; then
	ui="${XDG_SESSION_TYPE}"
fi

ui="$(basename "${ui}")"

# Colors
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

colors=("black" "red" "green" "yellow" "blue" "magenta" "cyan" "white")

if [[ $1 = "red" ]]; then
        c0="${reset}${red}"
elif [[ $1 = "green" ]]; then
        c0="${reset}${green}"
elif [[ $1 = "yellow" ]]; then
        c0="${reset}${yellow}"
elif [[ $1 = "blue" ]]; then
        c0="${reset}${blue}"
elif [[ $1 = "magenta" ]]; then
        c0="${reset}${magenta}"
elif [[ $1 = "cyan" ]]; then
        c0="${reset}${cyan}"
elif [[ $1 = "white" ]]; then
        c0="${reset}${white}"
else
    c0="${reset}${blue}"
fi

lc="${reset}${white}"
ic="${reset}"

## Output
cat <<EOF

${c0}        ◢◣          ${lc}  ${ic}${USER}${reset}
${c0}       ◢██◣         ${lc}  ${ic}${host}${reset}
${c0}      ◢████◣        ${lc}  ${ic}${kernel}${reset}
${c0}      ◥█████◣       ${lc}  ${ic}${uptime}${reset}
${c0}    ◢████████◣      ${lc}  ${ic}${memory}${reset}
${c0}   ◢███◤  ◥███◣     ${lc}  ${ic}${packages}${reset}
${c0}  ◢████    ████◣    ${lc}  ${ic}${shell}${reset}
${c0}  █◤          ◥█    ${lc}  ${ic}${ui}${reset}
EOF
